ALTER TABLE public.runs ADD COLUMN IF NOT EXISTS api_cost_cents INTEGER DEFAULT 0;
ALTER TABLE public.runs ADD COLUMN IF NOT EXISTS model_used TEXT DEFAULT NULL;
ALTER TABLE public.runs ADD COLUMN IF NOT EXISTS tokens_used INTEGER DEFAULT 0;